let header = document.querySelector('#header');
// Developer | Data Scientist | UI/UX Designer
let anim = [
    { t: "D_", ms: 75 },
    { t: "De_", ms: 75 },
    { t: "Dev_", ms: 75 },
    { t: "Deve_", ms: 75 },
    { t: "Develo_", ms: 75 },
    { t: "Develop_", ms: 75 },
    { t: "Develope_", ms: 75 },
    { t: "Developer_", ms: 75 },
    { t: "Developer _", ms: 75 },
    { t: "Developer |_", ms: 75 },
    { t: "Developer | _", ms: 75 },
    { t: "Developer | D_", ms: 75 },
    { t: "Developer | Da_", ms: 75 },
    { t: "Developer | Dat_", ms: 75 },
    { t: "Developer | Data_", ms: 75 },
    { t: "Developer | Data _", ms: 75 },
    { t: "Developer | Data S_", ms: 75 },
    { t: "Developer | Data Sc_", ms: 75 },
    { t: "Developer | Data Sci_", ms: 75 },
    { t: "Developer | Data Scie_", ms: 75 },
    { t: "Developer | Data Scien_", ms: 75 },
    { t: "Developer | Data Scient_", ms: 75 },
    { t: "Developer | Data Scienti_", ms: 75 },
    { t: "Developer | Data Scientis_", ms: 75 },
    { t: "Developer | Data Scientist_", ms: 75 },
    { t: "Developer | Data Scientist _", ms: 75 },
    { t: "Developer | Data Scientist |_", ms: 75 },
    { t: "Developer | Data Scientist | _", ms: 75 },
    { t: "Developer | Data Scientist | U_", ms: 75 },
    { t: "Developer | Data Scientist | UI_", ms: 75 },
    { t: "Developer | Data Scientist | UI/_", ms: 75 },
    { t: "Developer | Data Scientist | UI/U_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX _", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX D_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX De_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Des_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Desi_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Desig_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Design_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Designe_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Designer_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Designer", ms: 5000 },
    { t: "Developer | Data Scientist | UI/UX Designe_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Design_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Desig_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Desi_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX Des_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX De_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX D_", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX _", ms: 75 },
    { t: "Developer | Data Scientist | UI/UX_", ms: 75 },
    { t: "Developer | Data Scientist | UI/U_", ms: 75 },
    { t: "Developer | Data Scientist | UI/_", ms: 75 },
    { t: "Developer | Data Scientist | UI_", ms: 75 },
    { t: "Developer | Data Scientist | U_", ms: 75 },
    { t: "Developer | Data Scientist | _", ms: 75 },
    { t: "Developer | Data Scientist |_", ms: 75 },
    { t: "Developer | Data Scientist _", ms: 75 },
    { t: "Developer | Data Scientist_", ms: 75 },
    { t: "Developer | Data Scientis_", ms: 75 },
    { t: "Developer | Data Scienti_", ms: 75 },
    { t: "Developer | Data Scient_", ms: 75 },
    { t: "Developer | Data Scien_", ms: 75 },
    { t: "Developer | Data Scie_", ms: 75 },
    { t: "Developer | Data Sci_", ms: 75 },
    { t: "Developer | Data Sc_", ms: 75 },
    { t: "Developer | Data S_", ms: 75 },
    { t: "Developer | Data _", ms: 75 },
    { t: "Developer | Data_", ms: 75 },
    { t: "Developer | Dat_", ms: 75 },
    { t: "Developer | Da_", ms: 75 },
    { t: "Developer | D_", ms: 75 },
    { t: "Developer | _", ms: 75 },
    { t: "Developer |_", ms: 75 },
    { t: "Developer _", ms: 75 },
    { t: "Developer_", ms: 75 },
    { t: "Develope_", ms: 75 },
    { t: "Develop_", ms: 75 },
    { t: "Develo_", ms: 75 },
    { t: "Deve_", ms: 75 },
    { t: "Dev_", ms: 75 },
    { t: "De_", ms: 75 },
    { t: "D_", ms: 75 },
    { t: "_", ms: 75 },
    { t: "D_", ms: 75 },
    { t: "De_", ms: 75 },
    { t: "Dev_", ms: 75 },
    { t: "Deve_", ms: 75 },
    { t: "Develo_", ms: 75 },
    { t: "Develop_", ms: 75 },
    { t: "Develope_", ms: 75 },
    { t: "Developer", ms: 3000 },
    { t: "Develope_", ms: 75 },
    { t: "Develop_", ms: 75 },
    { t: "Develo_", ms: 75 },
    { t: "Deve_", ms: 75 },
    { t: "Dev_", ms: 75 },
    { t: "De_", ms: 75 },
    { t: "D_", ms: 75 },
    { t: "_", ms: 75 },
    { t: "D_", ms: 75 },
    { t: "Da_", ms: 75 },
    { t: "Dat_", ms: 75 },
    { t: "Data_", ms: 75 },
    { t: "Data _", ms: 75 },
    { t: "Data S_", ms: 75 },
    { t: "Data Sc_", ms: 75 },
    { t: "Data Sci_", ms: 75 },
    { t: "Data Scie_", ms: 75 },
    { t: "Data Scien_", ms: 75 },
    { t: "Data Scient_", ms: 75 },
    { t: "Data Scienti_", ms: 75 },
    { t: "Data Scientis_", ms: 75 },
    { t: "Data Scientist", ms: 3000 },
    { t: "Data Scientis_", ms: 75 },
    { t: "Data Scienti_", ms: 75 },
    { t: "Data Scient_", ms: 75 },
    { t: "Data Scien_", ms: 75 },
    { t: "Data Scie_", ms: 75 },
    { t: "Data Sci_", ms: 75 },
    { t: "Data Sc_", ms: 75 },
    { t: "Data S_", ms: 75 },
    { t: "Data _", ms: 75 },
    { t: "Data_", ms: 75 },
    { t: "Dat_", ms: 75 },
    { t: "Da_", ms: 75 },
    { t: "D_", ms: 75 },
    { t: "_", ms: 75 },
    { t: "U_", ms: 75 },
    { t: "UI_", ms: 75 },
    { t: "UI/_", ms: 75 },
    { t: "UI/U_", ms: 75 },
    { t: "UI/UX_", ms: 75 },
    { t: "UI/UX _", ms: 75 },
    { t: "UI/UX D_", ms: 75 },
    { t: "UI/UX De_", ms: 75 },
    { t: "UI/UX Des_", ms: 75 },
    { t: "UI/UX Desi_", ms: 75 },
    { t: "UI/UX Desig_", ms: 75 },
    { t: "UI/UX Design_", ms: 75 },
    { t: "UI/UX Designe_", ms: 75 },
    { t: "UI/UX Designer", ms: 3000 },
    { t: "UI/UX Designe_", ms: 75 },
    { t: "UI/UX Design_", ms: 75 },
    { t: "UI/UX Desig_", ms: 75 },
    { t: "UI/UX Desi_", ms: 75 },
    { t: "UI/UX Des_", ms: 75 },
    { t: "UI/UX De_", ms: 75 },
    { t: "UI/UX D_", ms: 75 },
    { t: "UI/UX _", ms: 75 },
    { t: "UI/UX_", ms: 75 },
    { t: "UI/U_", ms: 75 },
    { t: "UI/_", ms: 75 },
    { t: "UI_", ms: 75 },
    { t: "U_", ms: 75 },
    { t: "_", ms: 75 },
    
    
];
let stepDenominator = 1;
if (window.localStorage.stepDenominator)
    stepDenominator = window.localStorage.stepDenominator;
let i = 0;
let update = () => {
    let step = anim[i];
    header.innerText = step.t;
    i++;

    if (i < anim.length)
        setTimeout(update, step.ms / stepDenominator);
    else {
        i = 0;
        setTimeout(update, step.ms * 10);
    }
}
update();